// Game Data: Characters, Skills, Evolutions, Quests, Shop & Localization

const I18N = {
    ru: {
        gameTitle: "КОТОПОКАЛИПСИС: ВЫЖИВАНИЕ",
        subtitle: "Котики против Зомби",
        play: "В БОЙ!",
        upgrades: "ТАЛАНТЫ",
        selectHero: "ВЫБОР КОТИКА",
        quests: "КВЕСТЫ",
        back: "НАЗАД",
        coins: "Монеты",
        level: "Уровень",
        time: "Время",
        kills: "Убито",
        hp: "Здоровье",
        paused: "ПАУЗА",
        resume: "ПРОДОЛЖИТЬ",
        toMenu: "В МЕНЮ",
        levelUp: "НОВЫЙ УРОВЕНЬ!",
        chooseUpgrade: "Выберите улучшение для котика:",
        reroll: "Другие карты",
        freeRerollAd: "Обновить (Реклама)",
        gameOver: "ИГРА ОКОНЧЕНА",
        victory: "ПОБЕДА! ВЫЖИЛ!",
        survivedTime: "Время выживания",
        monstersDefeated: "Побеждено зомби",
        coinsEarned: "Собрано монет",
        revive: "ВОСКРЕСНУТЬ (РЕКЛАМА)",
        doubleCoins: "УДВОИТЬ МОНЕТЫ (РЕКЛАМА)",
        restart: "ЗАНОВО",
        maxLevel: "МАКС. УР.",
        upgradeCost: "Цена",
        buy: "Купить",
        locked: "Закрыто",
        select: "Выбрать",
        selected: "Выбран",
        controlsHint: "WASD / Стрелки / Экранный джойстик / Пробел (Рывок)",
        soundOn: "Звук: ВКЛ",
        soundOff: "Звук: ВЫКЛ",
        dash: "РЫВОК",
        chestTitle: "ТАИНСТВЕННЫЙ СУНДУК!",
        chestOpen: "ОТКРЫТЬ!",
        chestReward: "Награды сундука:",
        bossAlert: "ВНИМАНИЕ! ПОЯВИЛСЯ БОСС!",
        evolutionTitle: "СУПЕР-ЭВОЛЮЦИЯ ОРУЖИЯ!",
        record: "Рекорд",
        afkWarning: "НЕ СТОЙ НА МЕСТЕ! ВРАГИ В ЯРОСТИ!",
        heroStatsHp: "Здоровье",
        heroStatsSpeed: "Скорость",

        // Heroes
        hero_barsik: "Барсик",
        hero_barsik_desc: "Храбрый рыжий кот. Оружие: Рыбий бумеранг. ⚠️ ХАРДКОР: 95 HP, враги бегут быстрее!",
        hero_murzik: "Мурзик",
        hero_murzik_desc: "Быстрый ниндзя. Оружие: Клубок ниток. +20% скорости.",
        hero_pukhlyash: "Пухляш",
        hero_pukhlyash_desc: "Пушистый крепыш. Оружие: Мурчащая аура. +50% HP.",

        // Skills
        skill_fish_name: "Рыбный бумеранг",
        skill_fish_desc: "Летит во врагов, пробивает их и возвращается котику.",
        skill_yarn_name: "Клубок ниток",
        skill_yarn_desc: "Рикошетит между зомби, нанося урон нескольким целям.",
        skill_aura_name: "Мурчащая аура",
        skill_aura_desc: "Периодический звуковой мур-импульс поражает всех вокруг.",
        skill_laser_name: "Лазерная указка",
        skill_laser_desc: "Смертоносный красный луч испепеляет ближайшего зомби.",
        skill_slipper_name: "Тапок возмездия",
        skill_slipper_desc: "Тяжелый домашний тапок наносит критический урон.",
        skill_claws_slash_name: "Вихрь Когтей",
        skill_claws_slash_desc: "Круговой разрез когтями вокруг котика, рассекающий толпы врагов.",
        skill_valerian_name: "Банка Валерьянки",
        skill_valerian_desc: "Бросок флакона ядовитой валерьянки. Токсичная лужа замедляет и растворяет зомби.",
        skill_mine_name: "Мяу-Мины",
        skill_mine_desc: "Сбрасывает тикающие кошачьи мины, детонирующие при приближении врагов.",
        
        // Passives
        skill_catnip_name: "Кошачья мята",
        skill_catnip_desc: "+15% скорости атаки и +10% скорости бега.",
        skill_milk_name: "Свежее молочко",
        skill_milk_desc: "Пассивно восстанавливает 3 HP каждые 2 секунды.",
        skill_claws_name: "Острые когти",
        skill_claws_desc: "+20% к урону всех кошачьих атак.",
        skill_magnet_name: "Магнитная лапка",
        skill_magnet_desc: "+40% к радиусу притягивания рыбы и монет.",
        skill_armor_name: "Густая шерстка",
        skill_armor_desc: "-15% входящего урона и +25 к максимальному HP.",
        skill_static_name: "Статический Мех",
        skill_static_desc: "Электризует шерсть при беге. Раз в 3 секунды бьет молнией по ближайшим врагам.",

        // Evolutions
        evo_shark_name: "Золотая Акула-Меч",
        evo_shark_desc: "Эволюция (Рыба + Когти). Огромная акула непрерывно крушит всё вокруг!",
        evo_web_name: "Плазменная Паутина",
        evo_web_desc: "Эволюция (Клубок + Мята). Электрические нити связывают зомби в смертельную сеть.",
        evo_dome_name: "Священный Мур-Купол",
        evo_dome_desc: "Эволюция (Аура + Шерстка). Постоянный световой барьер с колоссальным отталкиванием.",
        evo_beam_name: "Орбитальный Луч «МЯУ-1»",
        evo_beam_desc: "Эволюция (Лазер + Магнит). 3 вращающихся лазера распыляют зомби на атомы.",
        evo_barrage_name: "Град Бабушкиных Тапок",
        evo_barrage_desc: "Эволюция (Тапок + Молочко). Бесконечный ковровый обстрел тяжелыми тапками.",
        evo_wolverine_name: "Лапы Росомахи",
        evo_wolverine_desc: "Эволюция (Вихрь Когтей + Когти). Смертоносные крестовые разрезы адамантиевыми когтями!",
        evo_valerian_storm_name: "Шторм Валерьянки",
        evo_valerian_storm_desc: "Эволюция (Валерьянка + Мята). Гигантский токсичный вихрь, затягивающий и растворяющий зомби.",

        // Talents (Meta Shop)
        talent_hp: "Живучесть",
        talent_hp_desc: "+15 к базовому максимальному здоровью",
        talent_dmg: "Сила лап",
        talent_dmg_desc: "+10% к базовому урону всех атак",
        talent_speed: "Ловкость",
        talent_speed_desc: "+8% к базовой скорости передвижения",
        talent_greed: "Кошачья жадность",
        talent_greed_desc: "+15% к шансу и стоимости выпадающих монет",
        talent_magnet: "Интуиция",
        talent_magnet_desc: "+25% к радиусу сбора предметов",

        // Quests
        quest_survive_60: "Выжить 1 минуту",
        quest_survive_180: "Выжить 3 минуты",
        quest_survive_300: "Выжить 5 минут",
        quest_kills_100: "Уничтожить 100 зомби",
        quest_kills_500: "Уничтожить 500 зомби",
        quest_boss_vacuum: "Победить Робота-Пылесоса",
        quest_make_evo: "Создать супер-эволюцию оружия",
        quest_reach_lvl_15: "Достичь 15 уровня за один бой"
    },
    en: {
        gameTitle: "CATPOCALYPSE: SURVIVOR",
        subtitle: "Cats vs Zombies",
        play: "BATTLE!",
        upgrades: "TALENTS",
        selectHero: "CHOOSE CAT",
        quests: "QUESTS",
        back: "BACK",
        coins: "Coins",
        level: "Level",
        time: "Time",
        kills: "Kills",
        hp: "Health",
        paused: "PAUSED",
        resume: "RESUME",
        toMenu: "TO MENU",
        levelUp: "LEVEL UP!",
        chooseUpgrade: "Choose an upgrade:",
        reroll: "Reroll",
        freeRerollAd: "Reroll (Watch Ad)",
        gameOver: "GAME OVER",
        victory: "VICTORY! SURVIVED!",
        survivedTime: "Survived Time",
        monstersDefeated: "Zombies Defeated",
        coinsEarned: "Coins Gathered",
        revive: "REVIVE (WATCH AD)",
        doubleCoins: "DOUBLE COINS (WATCH AD)",
        restart: "PLAY AGAIN",
        maxLevel: "MAX",
        upgradeCost: "Cost",
        buy: "Buy",
        locked: "Locked",
        select: "Select",
        selected: "Selected",
        controlsHint: "WASD / Arrows / Joystick / Space (Dash)",
        soundOn: "Sound: ON",
        soundOff: "Sound: OFF",
        dash: "DASH",
        chestTitle: "MYSTERY CHEST!",
        chestOpen: "OPEN!",
        chestReward: "Chest Rewards:",
        bossAlert: "WARNING! BOSS HAS APPEARED!",
        evolutionTitle: "SUPER WEAPON EVOLUTION!",
        record: "Record",
        afkWarning: "DON'T STAND STILL! ENEMIES ENRAGED!",
        heroStatsHp: "Health",
        heroStatsSpeed: "Speed",

        hero_barsik: "Barsik",
        hero_barsik_desc: "Brave ginger warrior. Weapon: Fish Boomerang. ⚠️ HARDCORE: 95 HP, faster enemy waves!",
        hero_murzik: "Murzik",
        hero_murzik_desc: "Agile ninja cat. Weapon: Yarn Ball. +20% Speed.",
        hero_pukhlyash: "Chonky",
        hero_pukhlyash_desc: "Fluffy tank. Weapon: Purr Aura. +50% HP.",

        skill_fish_name: "Fish Boomerang",
        skill_fish_desc: "Flies forward, piercing enemies and returning back.",
        skill_yarn_name: "Yarn Ball",
        skill_yarn_desc: "Bounces between zombies dealing damage to groups.",
        skill_aura_name: "Purr Aura",
        skill_aura_desc: "A soothing sound wave hurts all nearby zombies periodically.",
        skill_laser_name: "Laser Pointer",
        skill_laser_desc: "Deadly red beam vaporizes the closest threat.",
        skill_slipper_name: "Flying Slipper",
        skill_slipper_desc: "Heavy household slipper knocks out enemies.",
        skill_claws_slash_name: "Whirlwind Claws",
        skill_claws_slash_desc: "Circular slash cleaving through all nearby enemies.",
        skill_valerian_name: "Valerian Splash",
        skill_valerian_desc: "Throws a toxic valerian potion puddle that slows and melts zombies.",
        skill_mine_name: "Meow Mines",
        skill_mine_desc: "Drops ticking yarn bombs that explode in a massive radius.",

        skill_catnip_name: "Catnip Frenzy",
        skill_catnip_desc: "+15% attack speed and +10% move speed.",
        skill_milk_name: "Fresh Milk",
        skill_milk_desc: "Regenerates 3 HP every 2 seconds.",
        skill_claws_name: "Sharp Claws",
        skill_claws_desc: "+20% bonus damage to all attacks.",
        skill_magnet_name: "Magnet Paw",
        skill_magnet_desc: "+40% pickup radius for items and coins.",
        skill_armor_name: "Fluffy Fur",
        skill_armor_desc: "-15% damage taken and +25 Max HP.",
        skill_static_name: "Static Fur",
        skill_static_desc: "Charges fur electricity while running, periodically striking enemies with chain lightning.",

        evo_shark_name: "Golden Shark Blade",
        evo_shark_desc: "Evolution (Fish + Claws). Massive shark slices through hordes relentlessly!",
        evo_web_name: "Plasma Web",
        evo_web_desc: "Evolution (Yarn + Catnip). Electric threads bind and electrocute zombies.",
        evo_dome_name: "Sacred Meow Dome",
        evo_dome_desc: "Evolution (Aura + Armor). Constant radiant barrier that repels everything.",
        evo_beam_name: "Orbital Beam «MEOW-1»",
        evo_beam_desc: "Evolution (Laser + Magnet). 3 orbiting death rays disintegrate nearby foes.",
        evo_barrage_name: "Grandma Slipper Barrage",
        evo_barrage_desc: "Evolution (Slipper + Milk). Non-stop carpet bombing with slippers.",
        evo_wolverine_name: "Wolverine Claws",
        evo_wolverine_desc: "Evolution (Whirlwind Claws + Claws). Massive screen-clearing adamantium cross slashes!",
        evo_valerian_storm_name: "Valerian Vortex",
        evo_valerian_storm_desc: "Evolution (Valerian + Catnip). Giant toxic vortex pulling and dissolving zombies.",

        talent_hp: "Toughness",
        talent_hp_desc: "+15 Base Max Health",
        talent_dmg: "Paw Strength",
        talent_dmg_desc: "+10% Base Damage",
        talent_speed: "Agility",
        talent_speed_desc: "+8% Base Move Speed",
        talent_greed: "Cat Greed",
        talent_greed_desc: "+15% Bonus Coin Drop",
        talent_magnet: "Intuition",
        talent_magnet_desc: "+25% Item Pickup Magnet",

        quest_survive_60: "Survive 1 minute",
        quest_survive_180: "Survive 3 minutes",
        quest_survive_300: "Survive 5 minutes",
        quest_kills_100: "Defeat 100 zombies",
        quest_kills_500: "Defeat 500 zombies",
        quest_boss_vacuum: "Defeat Robot Vacuum Boss",
        quest_make_evo: "Create a weapon evolution",
        quest_reach_lvl_15: "Reach Level 15 in one run"
    }
};

const CHARACTERS = [
    {
        id: "barsik",
        nameKey: "hero_barsik",
        descKey: "hero_barsik_desc",
        sprite: "cat_barsik",
        maxHp: 95,
        speed: 195,
        startingWeapon: "fish",
        price: 0,
        unlocked: true
    },
    {
        id: "murzik",
        nameKey: "hero_murzik",
        descKey: "hero_murzik_desc",
        sprite: "cat_murzik",
        maxHp: 135,
        speed: 265,
        startingWeapon: "yarn",
        price: 250,
        unlocked: false
    },
    {
        id: "pukhlyash",
        nameKey: "hero_pukhlyash",
        descKey: "hero_pukhlyash_desc",
        sprite: "cat_pukhlyash",
        maxHp: 250,
        speed: 185,
        startingWeapon: "aura",
        price: 500,
        unlocked: false
    }
];

const SKILLS_DATABASE = {
    // Weapons
    fish: {
        id: "fish",
        type: "weapon",
        nameKey: "skill_fish_name",
        descKey: "skill_fish_desc",
        icon: "proj_fish",
        maxLevel: 5,
        baseDamage: 22,
        damagePerLevel: 7,
        cooldown: 1100,
        cooldownReduction: 100,
        speed: 340,
        evoId: "evo_shark",
        evoPassive: "claws"
    },
    yarn: {
        id: "yarn",
        type: "weapon",
        nameKey: "skill_yarn_name",
        descKey: "skill_yarn_desc",
        icon: "proj_yarn",
        maxLevel: 5,
        baseDamage: 18,
        damagePerLevel: 6,
        cooldown: 1300,
        cooldownReduction: 120,
        speed: 280,
        evoId: "evo_web",
        evoPassive: "catnip"
    },
    aura: {
        id: "aura",
        type: "weapon",
        nameKey: "skill_aura_name",
        descKey: "skill_aura_desc",
        icon: "aura_wave",
        maxLevel: 5,
        baseDamage: 14,
        damagePerLevel: 5,
        radius: 110,
        radiusPerLevel: 20,
        cooldown: 800,
        cooldownReduction: 60,
        evoId: "evo_dome",
        evoPassive: "armor"
    },
    laser: {
        id: "laser",
        type: "weapon",
        nameKey: "skill_laser_name",
        descKey: "skill_laser_desc",
        icon: "proj_laser",
        maxLevel: 5,
        baseDamage: 38,
        damagePerLevel: 14,
        cooldown: 1600,
        cooldownReduction: 150,
        range: 400,
        evoId: "evo_beam",
        evoPassive: "magnet"
    },
    slipper: {
        id: "slipper",
        type: "weapon",
        nameKey: "skill_slipper_name",
        descKey: "skill_slipper_desc",
        icon: "proj_slipper",
        maxLevel: 5,
        baseDamage: 45,
        damagePerLevel: 18,
        cooldown: 2000,
        cooldownReduction: 200,
        speed: 380,
        evoId: "evo_barrage",
        evoPassive: "milk"
    },
    claws_slash: {
        id: "claws_slash",
        type: "weapon",
        nameKey: "skill_claws_slash_name",
        descKey: "skill_claws_slash_desc",
        icon: "proj_claw_slash",
        maxLevel: 5,
        baseDamage: 32,
        damagePerLevel: 12,
        radius: 130,
        radiusPerLevel: 20,
        cooldown: 1500,
        cooldownReduction: 130,
        evoId: "evo_wolverine",
        evoPassive: "claws"
    },
    valerian: {
        id: "valerian",
        type: "weapon",
        nameKey: "skill_valerian_name",
        descKey: "skill_valerian_desc",
        icon: "proj_valerian",
        maxLevel: 5,
        baseDamage: 22,
        damagePerLevel: 8,
        cooldown: 2200,
        cooldownReduction: 180,
        duration: 3500,
        evoId: "evo_valerian_storm",
        evoPassive: "catnip"
    },
    meow_mine: {
        id: "meow_mine",
        type: "weapon",
        nameKey: "skill_mine_name",
        descKey: "skill_mine_desc",
        icon: "proj_mine",
        maxLevel: 5,
        baseDamage: 65,
        damagePerLevel: 22,
        cooldown: 2400,
        cooldownReduction: 200
    },

    // Passives
    catnip: {
        id: "catnip",
        type: "passive",
        nameKey: "skill_catnip_name",
        descKey: "skill_catnip_desc",
        icon: "drop_xp",
        maxLevel: 5,
        attackSpeedBonus: 0.12,
        moveSpeedBonus: 0.08
    },
    milk: {
        id: "milk",
        type: "passive",
        nameKey: "skill_milk_name",
        descKey: "skill_milk_desc",
        icon: "drop_heal",
        maxLevel: 5,
        regenAmount: 3,
        regenInterval: 2000
    },
    claws: {
        id: "claws",
        type: "passive",
        nameKey: "skill_claws_name",
        descKey: "skill_claws_desc",
        icon: "drop_coin",
        maxLevel: 5,
        damageMultiplier: 0.18
    },
    magnet: {
        id: "magnet",
        type: "passive",
        nameKey: "skill_magnet_name",
        descKey: "skill_magnet_desc",
        icon: "drop_clock",
        maxLevel: 5,
        magnetBonus: 0.40
    },
    armor: {
        id: "armor",
        type: "passive",
        nameKey: "skill_armor_name",
        descKey: "skill_armor_desc",
        icon: "drop_bomb",
        maxLevel: 5,
        damageReduction: 0.12,
        hpBonus: 25
    },
    static_fur: {
        id: "static_fur",
        type: "passive",
        nameKey: "skill_static_name",
        descKey: "skill_static_desc",
        icon: "skill_static",
        maxLevel: 5,
        damage: 40,
        damagePerLevel: 15,
        cooldown: 3200,
        cooldownReduction: 250
    },

    // SUPER WEAPON EVOLUTIONS
    evo_shark: {
        id: "evo_shark",
        type: "evolution",
        nameKey: "evo_shark_name",
        descKey: "evo_shark_desc",
        icon: "evo_shark",
        maxLevel: 1,
        baseDamage: 85,
        cooldown: 350
    },
    evo_web: {
        id: "evo_web",
        type: "evolution",
        nameKey: "evo_web_name",
        descKey: "evo_web_desc",
        icon: "evo_web",
        maxLevel: 1,
        baseDamage: 60,
        cooldown: 400
    },
    evo_dome: {
        id: "evo_dome",
        type: "evolution",
        nameKey: "evo_dome_name",
        descKey: "evo_dome_desc",
        icon: "evo_dome",
        maxLevel: 1,
        baseDamage: 45,
        radius: 200,
        cooldown: 300
    },
    evo_beam: {
        id: "evo_beam",
        type: "evolution",
        nameKey: "evo_beam_name",
        descKey: "evo_beam_desc",
        icon: "evo_beam",
        maxLevel: 1,
        baseDamage: 120,
        cooldown: 500
    },
    evo_barrage: {
        id: "evo_barrage",
        type: "evolution",
        nameKey: "evo_barrage_name",
        descKey: "evo_barrage_desc",
        icon: "evo_barrage",
        maxLevel: 1,
        baseDamage: 90,
        cooldown: 450
    },
    evo_wolverine: {
        id: "evo_wolverine",
        type: "evolution",
        nameKey: "evo_wolverine_name",
        descKey: "evo_wolverine_desc",
        icon: "evo_wolverine",
        maxLevel: 1,
        baseDamage: 110,
        cooldown: 750,
        radius: 220
    },
    evo_valerian_storm: {
        id: "evo_valerian_storm",
        type: "evolution",
        nameKey: "evo_valerian_storm_name",
        descKey: "evo_valerian_storm_desc",
        icon: "evo_valerian_storm",
        maxLevel: 1,
        baseDamage: 90,
        cooldown: 1800,
        duration: 5000
    }
};

const TALENTS = [
    { id: "hp", nameKey: "talent_hp", descKey: "talent_hp_desc", maxLvl: 5, baseCost: 50, costMult: 1.8, valPerLvl: 20 },
    { id: "dmg", nameKey: "talent_dmg", descKey: "talent_dmg_desc", maxLvl: 5, baseCost: 75, costMult: 1.8, valPerLvl: 0.1 },
    { id: "speed", nameKey: "talent_speed", descKey: "talent_speed_desc", maxLvl: 5, baseCost: 60, costMult: 1.7, valPerLvl: 0.08 },
    { id: "greed", nameKey: "talent_greed", descKey: "talent_greed_desc", maxLvl: 5, baseCost: 50, costMult: 1.6, valPerLvl: 0.2 },
    { id: "magnet", nameKey: "talent_magnet", descKey: "talent_magnet_desc", maxLvl: 5, baseCost: 40, costMult: 1.6, valPerLvl: 0.3 }
];

const QUESTS = [
    { id: "survive_60", textKey: "quest_survive_60", reward: 50, check: (data) => data.bestTime >= 60 },
    { id: "survive_180", textKey: "quest_survive_180", reward: 100, check: (data) => data.bestTime >= 180 },
    { id: "survive_300", textKey: "quest_survive_300", reward: 200, check: (data) => data.bestTime >= 300 },
    { id: "kills_100", textKey: "quest_kills_100", reward: 50, check: (data) => data.bestKills >= 100 },
    { id: "kills_500", textKey: "quest_kills_500", reward: 150, check: (data) => data.bestKills >= 500 },
    { id: "boss_vacuum", textKey: "quest_boss_vacuum", reward: 200, check: (data) => data.bossDefeated },
    { id: "make_evo", textKey: "quest_make_evo", reward: 250, check: (data) => data.evoCreated },
    { id: "reach_lvl_15", textKey: "quest_reach_lvl_15", reward: 100, check: (data) => data.maxLevelReached >= 15 }
];
